config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, only: [:show] do
    resources :stores, only: [:new, :index]
  end
  
  resources :stores, only: [:create, :show, :edit, :update, :index] do 
    resources :wines, only: [:new, :show, :edit]
  end

  resources :wines, only: [:show, :index, :create, :edit, :update] do
    resources :comments, only: [:new, :show, :index]
  end

  resources :comments, only: [:create, :show]
  
  root 'application#home'
  post 'users/:id/add_name', to: 'users#add_name', as: 'add_user_name'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :wine
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :user
  has_many :stores_wines
  has_many :wines, through: :stores_wines

  validates :name, :address, presence: true
end

app/models/stores_wine.rb
class StoresWine < ActiveRecord::Base
  belongs_to :store
  belongs_to :wine
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stores
  has_many :wines, through: :stores

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  #Sets user based on data received from Omniauth Facebook Login process
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|   #Finds or creates a user based on the auth.provider (Facebook) and the uid Facebook provides
      user.name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.password = Devise.friendly_token[0,20]   #This generates a random password for Facebook Login users, assuming they don't want to subsequently set a password
    end      
  end
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  has_many :comments
  has_many :stores_wines
  has_many :stores, through: :stores_wines
  accepts_nested_attributes_for :stores_wines

  validates :name, :price, :grape, :description, presence: true
  validates :color, presence: true, inclusion: { in: %w(Red White), message: "Must be either 'Red' or 'White'"}

  def print
    "#{self.name} - #{self.grape} - $#{self.price}" 
  end

  def add_store(params)
    store_id = params[:stores_wines_attributes][:"0"][:store_id].to_i
    inventory = params[:stores_wines_attributes][:"0"][:inventory].to_i
    if self.store_ids.include?(store_id)
      "This wine is already listed at the selected store"
    else
      self.stores_wines.build(store_id: store_id, wine_id: self.id, inventory: inventory)
      self.save
      "Wine has been successfully listed"
    end
  end

  def inventory_by_store(store)
    store.stores_wines.where(wine_id: self.id).pluck(:inventory)[0]
  end

  def stores_wine_by_store(store_id)
    self.stores_wines.where(store_id: store_id)
  end

  def self.varietals
    Wine.select(:grape).map(&:grape).uniq
  end

  def self.by_varietal(varietal)
    Wine.where(grape: varietal)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
  end

  #Devise action to tell it where to redirect after Omniauth sign in
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new 
    if params[:wine_id]
      @wine = Wine.find(params[:wine_id])
      @comment = @wine.comments.build
    else
      @comment = Comment.new
    end
  end

  def create
    @comment = Comment.create(comment_params)
    render json: @comment
  end

  def show
    if params[:wine_id]
      @wine = Wine.find(params[:wine_id])
      @comment = Comment.find(params[:comment_id])
    else 
      @comment = Comment.find(params[:id])
    end
  end

  def index 
    # only route available is an index route nested in wine#show route
    wine = Wine.find(params[:wine_id]) 
    @comments = wine.comments
    render json: @comments
  end

  private

  def comment_params
    params[:comment].permit(:content, :wine_id)
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def new
    if params[:user_id]
      @store = Store.new(user_id: params[:user_id])
    else
      @store = Store.new()
    end
  end

  def create
    @store = Store.new(store_params)

    if @store.save
      flash[:notice] = "Store has been created"
      redirect_to store_path(@store)
    else
      render :new
    end
  end

  def show
    @store = Store.find(params[:id])
  end

  def index
    if params[:user_id]
      @stores = User.find(params[:user_id]).stores
    else
      @stores = Store.all
    end

    # can render in either HTML or JSON
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @stores}
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    store = Store.find(params[:id])
    store.update(store_params)
    flash[:notice] = "Store has been updated"
    redirect_to store_path(store)
  end

  private

  def store_params
    params[:store].permit(:name, :address, :user_id)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def add_name
    user = User.find(params[:id])
    user.update(params[:user].permit(:name))
    flash[:notice] = "Name changed!"
    redirect_to user_path(user)
  end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController

  def show
    @wine = Wine.find(params[:id])
    if params[:store_id]
      @store = Store.find(params[:store_id])
    end

    # can render in either HTML or JSON
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @wine}
    end
  end

  def index
    if params[:varietal]
      @wines = Wine.by_varietal(params[:varietal])
    else
      @wines = Wine.all
    end

    # can render in either HTML or JSON
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @wines}
    end
  end

  def new
    if params[:store_id]
      @wine = Wine.new()
      @wine.stores_wines.build(store_id: params[:store_id])
    else
      @wine = Wine.new()
    end
  end

  def create
    if @wine = Wine.find_by(name: wine_new_params[:name])
      flash[:notice] = @wine.add_store(wine_new_params)
      redirect_to wine_path(@wine)
    else
      @wine = Wine.new(wine_new_params)
      if @wine.save
        flash[:notice] = "Wine has been successfully listed"
        redirect_to wine_path(@wine)
      else
        render :new
      end
    end
  end

  def edit
    @wine = Wine.find(params[:id])
    if params[:store_id]
      @store = Store.find(params[:store_id])
    end
  end

  def update
    wine = Wine.find(params[:id])
    flash[:notice] = "Wine has been updated"
    redirect_to wine_path(wine)
  end

  private

  def wine_new_params
    params[:wine].permit(:name, :description, :price, :color, :grape, stores_wines_attributes: [:store_id, :inventory])
  end

  def wine_edit_params
    params[:wine].permit(:name, :description, :price, :color, :grape)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def own_user_page?(user_id)
    user_id == current_user.id if user_signed_in?
  end

end

app/helpers/store_helper.rb
module StoreHelper
    
  def store_owner_logged_in?(store)
      (store.user_id == current_user.id) if user_signed_in?
  end

end

app/views/application/home.html.erb
<h1>Welcome!</h1>
<p>Wine Finder is a groundbreaking database that brings together wines and inventories at merchants around the world. Use it to compare and locate wines at stores near you. If you are a merchant or winery, add your stores and inventory to be viewed by customers online.</p>

<h3>
  <a onclick="showStores()">Browse all Stores</a>
</h3>

<h3>
  <a onclick="showWines()">Browse all Wines</a>
</h3>

app/views/comments/index.html.erb
<h1>Comments:</h1>
<% @comments.each do |comment| %>
  <%= comment.content %><br>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_for @comment do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <% if @wine %>
    <%= f.hidden_field :wine_id %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>Comment:</h1>
<p><%= @comment.content %></p>

app/views/layouts/_validation_errors.html.erb
<!--  layouts#_validation_errors  -->

<% if model.errors.any? %>
  <div class="container-fluid alert alert-info">
      <%= pluralize(model.errors.count, "error") %>
      prohibited this <%= model.class.name %> from being saved:
 
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WineFinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <!--  navbar -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand text-primary" href="/">WineFinder</a>
        </div>
        <ul class="nav navbar-nav">
          <li> <%= link_to "All Stores", stores_path %> </li>
          <li> <%= link_to "All Wines", wines_path %> </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a href="<%= user_path(current_user) %>" ><span class="glyphicon glyphicon-user"></span> Profile</a></li>
            <li> <%= link_to destroy_user_session_path, method: "DELETE" do %><span class="glyphicon glyphicon-log-out"></span> Logout<% end %></li>
          <% else %>
            <li><a href="<%= new_user_registration_path %>" ><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="<%= new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <li><a href="<%= user_facebook_omniauth_authorize_path %>"><i class="fa fa-facebook-square"></i> Login via Facebook</a></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!--  flash messages -->
    <% if flash[:error] || flash[:notice] || flash[:alert] %>
      <div class="container-fluid alert alert-info">
        <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
        <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
        <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
      </div><br>
    <% end %>

    <!--  content -->
    <div id="main" class="container-fluid">
    <%= yield %>
    </div>

    <!--  ********** HANDLEBARS TEMPLATES **********   -->

    <!--  Handlebars template: showStores (index view)   -->
    <script id="show-stores-template" type="text/x-handlebars-template">
      {{#each this}}	
        {{> storePartial}}
      {{/each}}
    </script>	

   <!--  Handlebars template: storePartial   -->
    <script id="store-partial" type="text/x-handlebars-template">
      <ul class="list-group">
        <li class="list-group-item">
        <strong><a href="stores/{{ id }}">{{ name }}</a></strong>
        <br>
        <strong>{{ address }}</strong><br>
        </li>
      </ul> 
    </script>	
    
    <!--  Handlebars template: showWines (index view)  -->
    <script id="show-wines-template" type="text/x-handlebars-template">
      <ul class="list-group">
        {{#each this}}	
          <li class="list-group-item">
            <strong><a onclick="showWine(this)" data-id="{{id}}">{{ print }}</a></strong>
          </li>
        {{/each}}
      </ul>
    </script>	

    <!--  Handlebars template: showWine (show view)  -->
    <script id="show-wine-template" type="text/x-handlebars-template">
      <!--  wine information -->
      <h3>{{ name }}</h3>
      <strong>Type: </strong>{{ color }}<br>
      <strong>Varietal: </strong>{{ grape }}<br>
      <strong>Price: </strong>${{ price }}<br>
      <strong>Description: </strong>{{ description }}<br>

      <!--  comments  -->
      <div>
        <h3>Comments:</h3>
          <div id="show-comments">
            {{#each comments}}	
              {{ content }}<br>
            {{/each}}
          </div> 
        <div id="post-comment">
          <a onclick="newCommentForm(this)" data-wineid="{{id}}">Post a Comment</a>
          <!--  new comment form to be appended here   -->
        </div>
      </div>

      <!--  stores where wine is sold  -->
      <h3>Stores Selling this Wine:</h3>
        {{#each stores}}	
          {{> storePartial }}
        {{/each}}
    </script>	

    <!--  new comment template  -->
    <script id="comment-form-template" type="text/x-handlebars-template">
      <form id="comment-form">
        Content: <input type="text" name="comment[content]">
        <input type="hidden" name="comment[wine_id]" value="{{this}}"> <!--  'this' is the wineId passed in  -->
        <input type="submit" value="Post Comment">
      </form>
    </script>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
  </body>
</html>

app/views/stores/_form.html.erb
<!--  stores#_form  -->

<%= form_for @store do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.hidden_field :user_id %>
  <%= f.submit %>
<% end %>

app/views/stores/_store.html.erb
<!--  stores#_store  -->

<ul class="list-group">
  <li class="list-group-item">
  <strong><%= link_to store.name, store_path(store) %></strong>
  <% if @wine %>
    <span class="badge">Inventory: <%= @wine.inventory_by_store(store) %></span><br>
  <% else %>
    <span class="badge"><%= store.wines.count %> Wines</span><br>
  <% end %>
  <strong><%= store.address %></strong><br>
  </li>
</ul>

app/views/stores/edit.html.erb
<!--  stores#edit  -->

<h2>Edit Store:</h2>
<%= render partial: "form", locals: {store: @store} %>

app/views/stores/index.html.erb
<!--  stores#index -->

<!--  store information -->
<%= render @stores %>

app/views/stores/new.html.erb
<!--  stores#new  -->

<!--  validation errors -->
<%= render partial: "/layouts/validation_errors", locals: {model: @store} %>

<!--  form -->
<h2>New Store:</h2>
<%= render partial: "form", locals: {store: @store} %>

app/views/stores/show.html.erb
<!--  stores#show  -->

<!--  store details  -->
<h3><%= @store.name %></h3>
<strong><%= @store.address %></strong><br>
<strong>Owner: </strong><%= link_to @store.user.name, user_path(@store.user) %><br>
<strong>Contact: </strong><%= @store.user.email %><br><br>

<!--  edit store button -->
  <%= link_to("Edit Store", edit_store_path(@store), class: "btn btn-default") if store_owner_logged_in?(@store) %>
<br><br>

<!--  display wines at this store-->
<h3>Wines at this Store <span class="label label-default"><%= @store.wines.count %></span>:
  <!--  list new wine button  -->
  <%= link_to("List a Wine", new_store_wine_path(@store), class: "btn btn-default pull-right") if store_owner_logged_in?(@store) %>
</h3>
<ul class="list-group">
  <%= render @store.wines, locals: {store: @store} %>
</ul>

app/views/users/show.html.erb
<!--  user#show -->

<!--  user profile information -->
<div class="panel panel-default">
  <div class="panel-heading">Profile</div>
</div>
<img src="<%= @user.image %>" width=50><br>
<% if own_user_page?(@user.id) %>
  <%= form_tag add_user_name_path(@user), method: "post" do %>
    <strong>Name: </strong><%= text_field_tag 'user[name]', @user.name %>
    <%= submit_tag "Submit" %>
  <% end %>
<% else %>
  <strong>Name: </strong><%= @user.name %><br>
<% end %>
<strong>Email: </strong><%= @user.email %><br>
<%= link_to("Update or Cancel Account", edit_user_registration_path, class: "btn btn-default") if own_user_page?(@user.id) %><br><br><br>

<!--  display user's stores -->
<div class="panel panel-default">
  <div class="panel-heading"><%= link_to "Stores", user_stores_path(@user) %></div>
</div>
<%= render @user.stores %>

<!--  button to create new store -->
<%= link_to("Set up a Store", new_user_store_path(current_user), class: "btn btn-default") if own_user_page?(@user.id) %>

app/views/wines/_form.html.erb
<!--  wines#form -->

<%= form_for @wine do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :color %>
  <%= f.text_field :color %><br>
  <%= f.label "Varietal" %>
  <%= f.text_field :grape %><br>
  <%= f.label :price %>
  <%= f.number_field :price, step: :any %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description, size: "30x5" %><br>
  <% if !@store %>
    <%= f.fields_for :stores_wines do |s| %>
      <%= s.hidden_field :store_id %>
      <%= s.label :inventory %>
      <%= s.number_field :inventory %><br>
    <% end %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/wines/_wine.html.erb
<!--  wines#wine  -->

<li class="list-group-item">
<% if @store %>
  <strong><%= link_to wine.print, store_wine_path(@store, wine) %></strong>
  <span class="badge">Inventory: <%= wine.inventory_by_store(@store) %></span><br>
<% else %>
  <strong><%= link_to wine.print, wine_path(wine) %></strong>
<% end %>
</li>

app/views/wines/edit.html.erb
<!--  wines#edit -->

<h2>Edit Wine:</h2>
<%= render partial: 'form', locals: {wine: @wine} %>

app/views/wines/index.html.erb
<!--  wines#index -->

<!--  filter wines -->
<%= form_tag(wines_path, method: "get") do %>
  Filter by Varietal: 
  <%= select_tag "varietal", options_from_collection_for_select(Wine.varietals, "itself", "itself"), include_blank: true %>
  <%= submit_tag "Filter" %>
  <%= link_to "Clear Filter", wines_path %>
<% end %>

<!--  display wines -->
<ul class="list-group">
  <%= render @wines %>
</ul>

app/views/wines/new.html.erb
<!--  wines#new -->

<!--  validation errors -->
<%= render partial: "/layouts/validation_errors", locals: {model: @wine} %>

<!--  form -->
<h2>List a Wine:</h2>
<%= render partial: 'form', locals: {wine: @wine} %>

app/views/wines/show.html.erb
<!--  wines#show -->

<!--  wine information -->
<h3><%= @wine.name %>
  <!--  edit wine button -->
  <%= link_to("Edit Wine", edit_store_wine_path(@store, @wine), class: "btn btn-default pull-right") if user_signed_in? && @store%>
</h3>
<strong>Type: </strong><%= @wine.color %><br>
<strong>Varietal: </strong><%= @wine.grape %><br>
<strong>Price: </strong>$<%= @wine.price %><br>
<strong>Description: </strong><%= @wine.description %><br><br>

<!--  comments  -->
<div>
  <a onclick="loadComments(this)" data-wine_id="<%=@wine.id%>">See Comments</a><br>
  <div id="show-comments">

  </div>
  <a href=<%=new_wine_comment_path(@wine)%>>Post a Comment</a>
</div>

<!--  stores where wine is sold -->
<h3>Stores Selling this Wine:</h3>
<%= render @wine.stores %>

<!--  comments#index display template -->
<script id="load-comments-template" type="text/x-handlebars-template">
  {{#each this}}	
    <p>{{ this.content }}</p>
  {{/each}}
</script>